### ISSUE TITLE
Add `List.NonEmpty.partition/unique` ?

### ISSUE THREAD

**Issue by kutyel** [turboMaCk/nonempty-list-alias-with-zipper#23]
Hi!

We (GWI) recently switched internally to use this library instead of our custom one (after finding a bug in our implementation 😓) and the only two functions missing are `partition` and `unique`. I fallback to the inner List and applied the List.Extra functions but maybe there is a better way to implement them?

Either way if you consider these two useful for this package I can provide a PR myself 😄

**Comment by turboMaCk** [comment]
hi @kutyel ! I'm interested in getting your PR in and to release.Feel fee to submit it.
